manifest:
  remotes:
    - name: upstream
      url-base: https://github.com/zmkfirmware
    - name: urob
      url-base: https://github.com/urob
    - name: caksoylar
      url-base: https://github.com/caksoylar
    - name: sparrowmike
      url-base: https://github.com/SparrowMike

  projects:
    - name: zmk
      remote: urob
      revision: main
      import: app/west.yml
    - name: zmk-rgbled-widget
      remote: caksoylar
      revision: main
    - name: sparrowmike
      remote: mikesparrow
      revision: urob
    - name: zmk-helpers
      remote: urob
      revision: main

  self:
    path: config
